backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

site_url: https://blog.vitau.mx
publish_mode: editorial_workflow
logo_url: https://vitau-logos.s3-us-west-1.amazonaws.com/vitau-logo-fullcolor.svg

collections:
  - name: "blog"
    identifier_field: url
    label: "Blog"
    folder: "src/pages/blog/"
    create: true
    slug: "{{category}}/{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Custom Url", name: "url", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Category", name: "category", widget: "string"}
